# Generated by Django 4.2.7 on 2024-01-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_test_testdates_delete_studenttest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='testName',
            field=models.SlugField(max_length=32, unique=True),
        ),
    ]
