# Generated by Django 4.2.7 on 2024-01-22 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testdate_delete_testdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test', verbose_name='Test'),
        ),
        migrations.AddConstraint(
            model_name='testdate',
            constraint=models.UniqueConstraint(fields=('test', 'course'), name='all_keys_unique_together'),
        ),
    ]
