# Generated by Django 4.2.7 on 2024-01-22 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_question_test_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=16)),
                ('takedate', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'No rendido'), (2, 'Por revisar'), (3, 'Revisado')])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test', verbose_name='Test')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentCode',
        ),
        migrations.AddConstraint(
            model_name='studenttest',
            constraint=models.UniqueConstraint(fields=('student', 'test'), name='one_test_per_student'),
        ),
    ]
