# Generated by Django 4.2.7 on 2024-01-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_studenttest_delete_studentcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'No rendido'), (2, 'Por revisar'), (3, 'Revisado')], default=1),
        ),
        migrations.AlterField(
            model_name='studenttest',
            name='takedate',
            field=models.DateTimeField(default=None),
        ),
    ]
