# Generated by Django 4.2.7 on 2024-01-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_studenttestquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='grade',
            field=models.FloatField(null=True),
        ),
    ]
