# Generated by Django 4.2.7 on 2024-01-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_studenttest_excelfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenttest',
            old_name='takedate',
            new_name='takeDateEnd',
        ),
        migrations.AddField(
            model_name='studenttest',
            name='takeDateStart',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
