# Generated by Django 4.2.7 on 2024-01-23 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_test_rubric_alter_studenttest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellRow', models.CharField(max_length=10)),
                ('cellColumn', models.CharField(max_length=10)),
                ('cellFormula', models.CharField(max_length=256)),
                ('cellValue', models.CharField(max_length=256)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question', verbose_name='Question')),
            ],
        ),
    ]
