# Generated by Django 4.2.7 on 2024-01-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=16)),
                ('rubric', models.FileField(upload_to='rubrics/')),
                ('zip_file', models.FileField(upload_to='tests/')),
            ],
        ),
    ]
