# Generated by Django 4.2.7 on 2024-01-14 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=8)),
                ('fullname', models.CharField(max_length=64)),
                ('semester', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course', verbose_name='Course')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testName', models.CharField(max_length=32)),
                ('questionNumber', models.CharField(max_length=3)),
                ('questionVersion', models.PositiveSmallIntegerField(default=1)),
                ('quesitonScore', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.AddField(
            model_name='fileupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('courseName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course', verbose_name='Course')),
                ('quesitonScore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.testquestions', verbose_name='Questions')),
                ('studentName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student', verbose_name='Student')),
            ],
        ),
    ]
